/**
 * `fromStartMulticastAsync(g)` generates independent copies of asynchronous g.
 * 
 * `g` is required to not have a type of `next`
 * 
 * The return value of each copy is the same as that of the original generator `g`. It also replays all values generated by `g` from the start.
 * 
 * `fromStartMulticastAsync(g)` never returns.
 * 
 * @param {number} [g] the asynchronous generator to multicast
 */

export { multicastAsync as fromStartMulticastAsync } from './multicastAsync'