/**
 * `step(distance)(g)` gets the elements of `g` separated `distance` items between each.
 * 
 * **Example** `step(5)(range())` generates 0, 5, 10, 15...
 * 
 * @param {number} [distance=0] The index difference of items of `g` to be generated by `step(distance)(g)`
 */

export function step<T> (distance: number = 1) {
  return function* (g: Generator<T>) {
    let current = 0
    for (let item of g) {
      if (current--) continue
      current = distance - 1
      yield item
    }
  }
}
