/**
 * 
 * `tagFeed(g)` generates `[e, n]`, where `e` is an item generated by `g` and `n` is the next value passed to generate `e`.
 * 
 * `tagFeed(g)` returns `[r, n]`, where `r` is the return value of `r` and `n` is the next value passed to end `g`.
 * 
 * @param g the generator whose feed is to be tagged
 * @returns 
 */

export function* tagFeed<T, TReturn = any, TNext = T>(g: Generator<T, TReturn, TNext>): Generator<(T | TNext)[], (TReturn | TNext)[], TNext> {
  let next: TNext
  let iterator: IteratorResult<T, TReturn>
  while (!(iterator = g.next(next)).done) {
    next = yield [iterator.value as T, next]
  }
  return [iterator.value as TReturn, next]
}
